# Generated by Django 2.1 on 2018-08-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_person_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='photo',
        ),
    ]
